name: Manual Workflow Approval
description: Pause a workflow and get user approval to continue
branding:
  icon: pause
  color: yellow
inputs:
  approvers:
    description: Required approvers
    required: true
  secret:
    description: Secret
    required: true
  minimum-approvals:
    description: Minimum number of approvals to progress workflow
    required: false
  issue-title:
    description: The custom subtitle for the issue
    required: false
  allow-workflow-initiator-as-approver:
    description: Whether or not to include the user who initiated the workflow as an approver.
    default: true
runs:
  using: docker
  image: docker://ghcr.io/trstringer/manual-approval:1.7.0
